### ISSUE TITLE
OSX Playback stops, window goes black

### ISSUE THREAD

**Issue by dustinjlandgraf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1330]
**OS:**
OSX 10.11.5 (15F34)

**Issue Descriptions:**
Playback will stop, interface will go black. only quitting and re-launching the app will allow you to start playback again.

**Steps to Reproduce:**
Open App, play music. Works as expected for a while, but eventually stops. Playback stops within first few seconds of a new song, and it seems to be after an advertisement plays, but I will have to confirm. 
![screenshot 2016-07-18 10 59 15](https://cloud.githubusercontent.com/assets/5217734/16921884/09a2de62-4cd9-11e6-9c0e-00a5989fdcc1.png)

**Comment by MarshallOfSound** [comment]
This is a chromium bug upstream.  Should be fixed in the next chromium version bump inside electron

**Comment by daveisfera** [comment]
I was seeing the same issue after basically every ad, but yesterday I updated to 10.11.6 and haven't seen the issue since.

**Comment by NickChristensen** [comment]
Updated to 10.11.6, this is still occurring routinely for me

**Comment by daveisfera** [comment]
I must have just been getting lucky or something, because it just happened to me again.
