### ISSUE TITLE
Autostart on Windows breaks across updates

### ISSUE THREAD

**Issue by ZephireNZ** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1505]
**OS:** Windows 10 Pro Build 14393

**Issue Descriptions:**  
When doing an automatic update, the startup launcher is not updated for the new version. When Windows is restarted, the old version will be started instead of the new version. This can be fixed by removing then readding the launcher either manually or within GPMDP, however it should really be done automatically by the application.

**Steps to Reproduce:**
1. Have outdated version of GPMDP
2. Enable application on startup (in "Desktop Settings")
3. Click the "update" button when prompted within the app
4. Observe version number of app
4. Restart Windows
5. Observe *old* version of app

**Comment by berryelectronics** [comment]
That would be because it creates an autostart for the version you activate it and GPMDP a new folder creates for the new Version. 
A fix would be to remove the autostart before it Updates and when that is finished the autostart gets added again

**Comment by MarshallOfSound** [comment]
This has been fixed in a recent update.  But if you enabled it before the update it will still be broken

**Comment by ZephireNZ** [comment]
This is the Location of the Startup shortcut, created in v 3.5.0: `C:\Users\Brynley\AppData\Local\GPMDP_3\app-3.5.0`

Unless it's been fixed after v3.5.0, it's still not working as intended as far as I can tell.
