### ISSUE TITLE
Freezing after playing music Windows 10

### ISSUE THREAD

**Issue by LordVaderXIII** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1528]
Windows 10 Anniversary update

Player freezes, no buttons work but sound still plays. Last FM scrobbling is on. 

Open player, choose song, wait 5 or so seconds and player wont respond.

**Comment by MarshallOfSound** [comment]
Fixed in latest Electron build

**Comment by BluJINonlee** [comment]
I just uninstalled and reinstalled, and it is still happening. Any suggestions?

**Comment by mthbaker** [comment]
I'm continuing to experience this as well.

**Comment by MarshallOfSound** [comment]
That's because although Electron is fixed.  We have not pushed an update yet
