### ISSUE TITLE
UI freaks out when using track pad or mouse on Surface Pro 4

### ISSUE THREAD

**Issue by insomnios** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1903]
**OS:** Windows 10 on surface pro 4

**Issue Descriptions:** UI freaks out with the track pad, jumping from the item I'm clicking on to many others. Will still let me click on the item i am hovering over, but secondary or scroll over functions are very hard to use. 

**Steps to Reproduce:** constant issue.

**Comment by eoinscanlon** [comment]
**OS :** Mac OS Sierra Version 10.12.2 Beta  (Also had issue before moving to beta!)

**Issue Description :**  UI and Images/Sections freak out and clip constantly.  Fullscreen album art no longer shows up properly.  I use this app a lot and still do despite the issue.  Here is a video of the issue.  https://streamable.com/tkxs

**Steps to Reproduce :** Sadly, just using the app.

**Comment by MarshallOfSound** [comment]
This was fixed in 4.0.3 guys...

**Comment by eoinscanlon** [comment]
I'm sorry, I am running 4.0.3.  I only came here after the update and it was still happening.

**Comment by insomnios** [comment]
Sorry, I had just recently updated again to check and see if the issue was resolved. Didn't realize see you new update had just come out. Thanks for fixing it, love your app!
