### ISSUE TITLE
Dark custom themes are hiding artist/album cover images.

### ISSUE THREAD

**Issue by nzchicken** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1938]
After upgrading to 4.0.3 from 4.0.2, the dark custom themes no longer displays artist/album cover page images. The image still displays for "Light" custom themes. Not sure if this is functioning as designed, however I'm fairly sure that on 4.0.2 (prior to google changing the style) the images were still there on dark themes.

**OS:** MAC OS X 10.12.1 Sierra

**Issue Descriptions:** Dark custom themes don't have an artist/album background image.

**Steps to Reproduce:** Under Desktop Settings -> Tick Custom Theme -> Select Dark Option. Browse a artist page, or album that you know has a background image, and it won't appear.

**Comment by MarshallOfSound** [comment]
This has been fixed upstream in the theming library

**Comment by captainnapalm** [comment]
This is not fixed for me on 4.0.5. I still don't see background images using the dark theme.
