### ISSUE TITLE
Last.fm missing scrobbles

### ISSUE THREAD

**Issue by gonzalo-rodriguez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2609]
**OS:** 
Windows 7

**Issue Descriptions:**
I have last.fm authenticated and working on the Player (and have even logged out and in again, just in case). However, since 4-5 days ago, most of my scrobbles appear as "Scrobbling now" in last.fm but not as actually scrobbled afterwards. Others, however, do appear as succesfully scrobbled.

**Steps to Reproduce:**
Reproduce a bunch of tracks with last.fm enabled, check that they actually appear as "Scrobbling now" on the last.fm website, check that later they don't appear as actually scrobbled.

**Comment by MarshallOfSound** [comment]
Almost certainly fixed in #2317

**Comment by gonzalo-rodriguez** [comment]
I tried the latest generated EXE for 4.4.0 and scrobbling seems to be a bit better, but it still misses a lot of scrobbles for no apparent reason. Anything I can do to help diagnose/fix?

**Comment by winfriedk** [comment]
Hi,

I've the same problem. I just installed the latest version on my Win 10 PC. Only very few of my heard tracks with this application appear in the travk list of last.fm. When I scrobble music tracks with the VLC player all is fine. So I assume there is no problem on the last.fm site.

**Comment by whiplash159** [comment]
Same problem here. I'm playing a playlist. If I go to my last.fm page I see that it shows the current song as scrobbling. But the previous songs are missing. Sometimes, after I open the last.fm page the songs afterwards appears in my last.fm profile. But not always. Sometimes songs are just missing - I play a whole album (10 songs for example) and only 3-4 of them appear in my profile.

**Comment by petuhovskiy** [comment]
Just updated to 4.4.0 and it looks like I have the similar problem. I've checked handler.js and for me change:playback-time event is not firing when the window is minimized. I am not sure if that should be fixed here or in gmusic.js. @MarshallOfSound , what do you think? 

Btw, if you have problems, you can try not to minimize GPMDP window and check if scrobbling works.

**Comment by TurbinoZ100000** [comment]
Can confirm, scrobbling works when window is not minimized. Should a new issue be opened for this since this one is closed?

**Comment by whiplash159** [comment]
I'm new to GitHub so I'm not sure about the exact procedure but, as no one seems to look at this more two weeks, probably a new bug has to be committed.

**Comment by ciam** [comment]
Have been experiencing similar issues on debian 9 on the latest version.

**Comment by erlonpr** [comment]
@MarshallOfSound I have the latest version (v4.4.1) of Google Play Music Desktop Player installed on my computer running Microsoft Windows 10 and the problem in scrobbling to Last.fm still continues for me.
It syncs with the Last.fm when I favorite a song, but not the scrobbling.

**Comment by blakkheimgw** [comment]
I'm facing the same issue : 
Linux Fedora
GPMDP 4.4.1

**Comment by XZaya** [comment]
Same issue on:
GPMDP 4.4.1
Windows 10

**Comment by v-skochko** [comment]
You need to do something with this! Same problem

**Comment by jostrander** [comment]
We really don't appreciate demands. It's already fixed but not released.

**Comment by TurbinoZ100000** [comment]
Wasn't it fixed in 4.5.0? I haven't had any issues with the current version.

**Comment by jostrander** [comment]
It's been fixed a few times, but Google has changed a few things on their end. This time we have a better fix which should hopefully last longer thanks to @MarshallOfSound.

**Comment by Mirtma** [comment]
Hello! Is there any new update? I still have a problem with saving scrobbles to LastFM
