### ISSUE TITLE
Open at login terminal warning

### ISSUE THREAD

**Issue by eyaln555** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2905]
OS:
MacOS 10.13.2

Issue Descriptions:
When "Automatically launch when I turn my computer on" is checked, every time I turn my computer on the terminal is launched with this warning:

Google Play Music Desktop Player[550:5100] *** WARNING: Textured window <AtomNSWindow: 0x7ff91e7157b0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

Steps to Reproduce:
Turn the computer on while having "Automatically launch when I turn my computer on" checked.

**Comment by jostrander** [comment]
GPMDP Version?

**Comment by eyaln555** [comment]
@jostrander version 4.4.1.

**Comment by jostrander** [comment]
The error can be ignored, it doesn't mean anything, however the terminal popping up and not closing automatically is the real issue here.

**Comment by eyaln555** [comment]
@jostrander I assumed the warning is meaningless. And you are right, the terminal not closing is my issue here.
Do you know maybe how to solve this?

**Comment by jostrander** [comment]
I don't have a solution for that. That functionality uses a third party library and as I don't have a mac to test with currently I can't diagnose the issue.

**Comment by MarshallOfSound** [comment]
This doesn't occur on my machine, I think it will either be fixed by an OS update or it will definitely go away when we update Electron versions and get a version of Electron that doesn't output that log 👍

**Comment by jwmann** [comment]
Still getting the issue of the Terminal not closing.
No warning though.

**Comment by cboteros-connexa** [comment]
This issue of having the terminal opened on OS start still happens.

@jostrander, I found something on the web which might be of help in here:

https://github.com/Teamwork/node-auto-launch/issues/28#issuecomment-222012448

**Comment by jvasalloupgrade** [comment]
I know this has been marked as closed, but still an issue. Same output as above:
`Last login: Wed Jun 13 08:48:59 on ttys000
num-administrator:~ user$ /Applications/Google\ Play\ Music\ Desktop\ Player.app/Contents/MacOS/Google\ Play\ Music\ Desktop\ Player ; exit;
2018-06-13 08:50:29.058 Google Play Music Desktop Player[1001:8706] *** WARNING: Textured window <AtomNSWindow: 0x7fb1b8763500> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Starting Sentry
error: ################### !! Update server down !! ##################
`
