### ISSUE TITLE
Media keys on keyboard is triggered twice.

### ISSUE THREAD

**Issue by Natherul** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3239]
**OS:**
WIndows 10
**GPMDP Version:**
4.6.0 I think, cant find any info in the application but its updated to latest that its asked me for.
**Issue Descriptions:**
Enabling Windows 10 system media service will cause my keyboard media keys to happen twice.
**Steps to Reproduce:**
Enable said option and use the media keys on a logitech G610

**Comment by Makishanuto** [comment]
Think this was fixed recently in master

**Comment by Plastermaster** [comment]
Have the same issue, but it seems to have something to do when the main window is minimized. Otherwise it works fine.

**Comment by Natherul** [comment]
update today, same issue persists and it does not matter if window is minimized or not (wont matter if window is in focus or not either).

**Comment by Alipoodle** [comment]
reproduce of #3156 #3014 #2364 #2253
> MarshallOfSound commented 27 days ago
Known and fixed in master

However I can still reproduce this.
This is mainly due to Windows Media Service + GPMDP Still both picking up on the Next Media Key it seems.

**Comment by MarshallOfSound** [comment]
I misdeclared #3156 as fixed, this is still a duplicate of #2364
