### ISSUE TITLE
Two buttons for mini player, one doesn't work

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3297]
https://i.imgur.com/DpGj17n.png

The little icon works.

**Comment by MarshallOfSound** [comment]
This should be fixed in the latest version

**Comment by navjinder** [comment]
I still see this issue @MarshallOfSound on Mac OSX 10.14.3

<img width="318" alt="image" src="https://user-images.githubusercontent.com/3472650/60276223-35349e00-98c9-11e9-967b-0cba9efc33d8.png">
