### ISSUE TITLE
Missing Icon on Mac OS

### ISSUE THREAD

**Issue by supermueller** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3308]
**OS:**

Mac OS Sierra 10.12.6

**GPMDP Version:**

4.6.1

**Issue Descriptions:**

The App Icon is missing in Finder and Dock

**Steps to Reproduce:**

Download GPMDP, unpack it ans open it. You will see the generic Mac OS app icon in the Finder and the Dock.

**Possible Solution**

It seems like the app icon file `electron.icns` is corrupted or missformated. I have re-saved the app icon using the app ”iConvert Icons“ replaced it in the app’s content folder (cleared the app cache on my mac; restart Finder and Dock) and then all works fine.

Please find the fixed icns-file attached.

[electron.icns.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2256782/electron.icns.zip)

**Comment by kamilpaluch** [comment]
For me the icon is missing but only on non retina external screens. When I move the dock to MacBook retina screen the icons appears just fine. Same issue in Finder. Icon is fine when Finder is on retina screen but breaks as soon as I move Finder to external non-retina display. Hope this helps. Thanks for amazing app!

**Comment by supermueller** [comment]
I have just tested the app on my MacBook pro and the icon looks fine. I still think it’s a wrong formatted or corrupted icns file.

**Comment by MarshallOfSound** [comment]
This has been fixed in master

**Comment by Chewieez** [comment]
I do not have an icon for GPMDP version 4.6.1 on Mac El Capitan 10.11.6.  I have downloaded and installed a fresh version from the website and it downloads and unzips and does not have an icon for the dock. The icon in the top tray shows when the app is running.

**Comment by dstarh** [comment]
@MarshallOfSound this is still happening for me on latest version

**Comment by bassmastry101** [comment]
@MarshallOfSound This issue is still happening in the latest build (4.6.1) on non-retina external displays. Please see screenshots for comparison.

Retina:
<img width="57" alt="Screen Shot 2019-03-27 at 11 11 27 AM" src="https://user-images.githubusercontent.com/12259118/55088058-75de0a80-5081-11e9-8f97-9cc842af08da.png">

Non-Retina:
![Screen Shot 2019-03-27 at 11 11 36 AM](https://user-images.githubusercontent.com/12259118/55088073-79719180-5081-11e9-8358-d449f13bc7d0.png)
