### ISSUE TITLE
Mac Os Sierra app icon is missing

### ISSUE THREAD

**Issue by caipivara** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3538]
Im unziping the app from https://www.googleplaymusicdesktopplayer.com/# but when I see the app listed on finder there is no icon in there.

![WhatsApp Image 2019-04-12 at 8 52 30 AM](https://user-images.githubusercontent.com/76348/56042360-8092d380-5d00-11e9-9886-6b59a761929a.jpeg)

This is not happening in Mac Os Mojave.

App Version: 4.6.1

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/e3e398fdf06e7805dd619bf374979ac7526f148b

**Comment by caipivara** [comment]
I was able to test it and it is not fixed yet.

![IMG-20190626-WA0007](https://user-images.githubusercontent.com/76348/60197491-166cd380-9805-11e9-81da-0a11b9d5c3f9.jpg)
![IMG-20190626-WA0008](https://user-images.githubusercontent.com/76348/60197492-166cd380-9805-11e9-9e96-1cdd6a65c702.jpg)
![IMG-20190626-WA0009](https://user-images.githubusercontent.com/76348/60197493-166cd380-9805-11e9-934a-20870a95e5cc.jpg)
