### ISSUE TITLE
Stuck on "Loading music library"

### ISSUE THREAD

**Issue by Azhag** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3640]
**OS:** 
Debian GNU/Linux rodete

**GPMDP Version:** 
4.6.1

**Issue Descriptions:** 
Since last week, opening the app does not show anything, instead I get stuck on a "Loading music library" page

**Steps to Reproduce:**
1. Open the app
2. Stuck on loading page, nothing working.

**Comment by ryanjuza** [comment]
Same issue on Windows on all PC's I have using it.
1. Open GPMDP from pinned taskbar icon, system icon, or other method.
2. Player never gets beyond "Loading Music Library," progress bar does not move at all.

**Comment by ikstro** [comment]
I have the same problem от Windows 10 on Laptop and Desktop.

1. Start GPMDP 4.6.1 from Menu or Desktop Icon.
2. Player stops on window "Загрузка Фонотеки" (Loading Music Library).
3. Uninstall GPMDP and clear the registry .
4. Install GPMDP 4.6.1
5
![Фигня](https://user-images.githubusercontent.com/56383911/66547550-273d1d00-eb48-11e9-9514-fd4384efbdc4.png)
. Player stops on window "Загрузка Фонотеки" (Loading Music Library).

**Comment by antonot** [comment]
Same problem on MacOS even after deleting the cache.

**Comment by rameezv** [comment]
+1 happening on Debian x64 for the last few days as well

**Comment by jason-mehmel** [comment]
+1 here too, installed newest version, Ubuntu Linux 18.04

**Comment by timmyleahy** [comment]
+1 Mac Pro, OSX 10.14.6, GPMDP 4.6.1

Did full uninstall (removed app and ~/Library/Applications/GPMDP dir) and reinstalled. Authenticated user account. Hanging on "Loading Music Library..." screen.

Tried downgrading to 4.6.0 and that made no difference, still hangs on "Loading Music Library..." screen after authenticating.

Not sure if this is related but I looked at the ~/Library/Applications/GPMDP/gpmdp.log and saw an error:

```
{"level":"info","message":"Application started.","timestamp":"2019-10-10T19:54:34.169Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2019-10-10T19:54:34.629Z"}
```

**Comment by Chronos-Sk** [comment]
Possibly related, but this loading issue first started for me when the website certificate expired (GH-3639).

**Comment by jatk** [comment]
Running into the same issue of Windows 10

**Comment by jostrander** [comment]
Not sure why this is happening. It's more than likely a problem in the player causing an error that prevents GPM from loading. If that's the case these steps may not work, but if you can try them anyway:

1. Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>G</kbd>
2. Enter (without quotes): "DEV_MODE"
3. Click Go
4. You should now be in dev mode, and able to open developer tools from either the menu or by using <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>i</kbd>
This is the main window console, you may see errors, take a screenshot or copy and paste and errors from this console.
In addition to this you can type `openGPMDevTools()` <kbd>Enter</kbd> and it will open another console, you may have more errors here, copy these as well.

**Comment by jatk** [comment]
> 
> 
> Not sure why this is happening. It's more than likely a problem in the player causing an error that prevents GPM from loading. If that's the case these steps may not work, but if you can try them anyway:
> 
>     1. Press CTRL + SHIFT + G
> 
>     2. Enter (without quotes): "DEV_MODE"
> 
>     3. Click Go
> 
>     4. You should now be in dev mode, and able to open developer tools from either the menu or by using CTRL + SHIFT + i
>        This is the main window console, you may see errors, take a screenshot or copy and paste and errors from this console.
>        In addition to this you can type `openGPMDevTools()` Enter and it will open another console, you may have more errors here, copy these as well.
Running into these errors: 
Console:
![image](https://user-images.githubusercontent.com/1661193/66720335-eb60bc80-edc0-11e9-8126-29c7b8c7c188.png)

GPMDevTools:
![image](https://user-images.githubusercontent.com/1661193/66720344-f74c7e80-edc0-11e9-8820-e32557f5d240.png)

**Comment by jostrander** [comment]
I don't have access to listen_v2.js, as I'm being served listen.js. However, that is a weird error being thrown. `window.customElements.upgrade` is a function when I test it on the current release, so it shouldn't be throwing an error.

**Comment by kerfall** [comment]
Same error on windows 10 started friday morning.
But youtube Music is still working tough.

**Comment by dobesv** [comment]
I get the same console errors as above.  If I clear cookies and reload, it asks me to login again, but after login it goes to the same place.

I wonder if it is trying to show some kind of "upgrade" UI to some users based on their account status, and that thing is failing to load in this app environment.

**Comment by sebsebmc** [comment]
In a regular Google Play Music tab window.customElements.upgrade is a native function, and chromestatus.com shows it as added in Chrome 68 https://chromestatus.com/features/5967337471606784

The package.json lists electron 3.18 which seems to be Chromium 66.0.3359.181

**Comment by sebsebmc** [comment]
I can confirm that the artifact from the WIP Electron 4 PR https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3588 does seem to get past the Loading Music Library screen. Hopefully this can get merged before listen_v2.js is rolled out to everyone.

**Comment by dobesv** [comment]
Ah interesting, maybe this just needs to ship a new build with newer version of the Chrome engine in it?

**Comment by b0g3r** [comment]
I see the same error for 4 days :(

**Comment by ddsol** [comment]
You can start it with the following `DEV_MODE` (see above) workaround:

On the openGPM devtools (see above) console, put a breakpoint on listen_v2, line one. Then refresh the page, and enter `window.customElements.upgrade = () => undefined` [enter] and then continue running the script. It magically doesn't need the `upgrade` function because just setting it to something that does nothing at all makes it work.

In any case, it allows you to use your GDP with some pain at startup. You can close the DevToolss (?? plural<sup>2</sup>) and use the player as normal from there on in.

**Comment by altblog** [comment]
Windows 10. DEV_MODE say:
Local\GPMDP_3\app-4.6.1\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js:38
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead.

Pls fix it!

**Comment by ddsol** [comment]
Fix available (for Windows, at least):

- Install [7zip](https://www.7-zip.org/)
- Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/)
- Make sure GDMP is closed, exited and shut down
- Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
- Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
- Open `app.asar` with 7zip (open as archive)
- In 7zip, navigate to `build\renderer\windows\GPMWebView\`
- Drag `index.js` from there to your desktop or some folder
- Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/))
- Change
  ```js
  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

  global.isGPM = true;
  ```
  to
  ```js
  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

  window.customElements.upgrade = window.customElements.upgrade || function(){};

  global.isGPM = true;
  ```
  (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
- Save it or it's as if you did nothing
- Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
- Close 7zip
- Start your music player, it should work now

**Comment by tpetersen50** [comment]
> Fix available (for Windows, at least):
> 
> * Install [7zip](https://www.7-zip.org/) (at your own risk)
> * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)
> * Make sure GDMP is closed, exited and shut down
> * Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
> * Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
> * Open `app.asar` with 7zip (open as archive)
> * In 7zip, navigate to `build\renderer\windows\GPMWebView\`
> * Drag `index.js` from there to your desktop or some folder
> * Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/) at your own risk)
> * Change
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   global.isGPM = true;
>   ```
>   
>   
>   to
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   window.customElements.upgrade = window.customElements.upgrade || function(){};
>   
>   global.isGPM = true;
>   ```
>   
>   
>   (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
> * Save it or it's as if you did nothing
> * Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
> * Close 7zip
> * Start your music player, it should work now
> * Clean up the straggling `index.js` and if you're happy, confident and brave, your `app.asar.backup`. Also, clean your desk.
> * Do this each time you want to run it.
> * Just kidding, it'll work from now on.

Seemed to work for me. Thanks!!!

**Comment by dobesv** [comment]
FWIW instead of copying the file out to edit it, I just used the edit option in the 7-zip right click menu, it copies it to a file for you and when you change that file it offers to update the zip file.

**Comment by ddsol** [comment]
Yes, but that doesn't work if Notepad is your default editor due to bad line ending handling. That's why the long version...

**Comment by dobesv** [comment]
Actually I made the change using notepad and it didn't cause a problem.

**Comment by ddsol** [comment]
My bad I never went to W10 because GetWindows10 gave me a bad taste continued with Windows Spyware integration. Of course MS improved Windows massively by adding LF support and I was unaware. Are there any other changes in W10 that are important or matter in any way I should be aware of? Nvm... this is not a chat room...

**Comment by dobesv** [comment]
For me, Windows 10 is the best Windows version.  Lots of little improvements all over the place.  Better notepad, dark mode, command line, etc..  But I know there are some in your face items that annoy people.  I think they might have annoyed me at first but over time I've gotten used to it and forgotten what they are.

**Comment by JAgostoni** [comment]
> Fix available (for Windows, at least):
> 
> * Install [7zip](https://www.7-zip.org/) (at your own risk)
> * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)

Worked great!  Instead of using Asar7zip I installed the asar NPM package:
`npm i -g asar`

Then I just extracted the package, backed-up/edited the file as you stated above, then re-packed it:
`asar e app.asar app`
... edit file ...
`asar p app app.asar`

**Comment by kolaval** [comment]
Can anybody share their fixed app.asar?

**Comment by cable729** [comment]
Same is happening to me (4.6.1), although youtube music mode works.

**Comment by eric-wag** [comment]
Happening for me on macOS mojave

**Comment by crayfishuk** [comment]
@tpetersen50 thanks! 
[app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

**Comment by ddsol** [comment]
It was actually me that came up with the fix. tpetersen50 just quoted me.

**Comment by tpetersen50** [comment]
> It was actually me that came up with the fix. tpetersen50 just quoted me.

Yep, I take no credit for the fix!

**Comment by kolaval** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Works, Thanks

**Comment by bjordan22** [comment]
@crayfishuk your file works for me too, thanks for making it easy

**Comment by rameezv** [comment]
@MarshallOfSound any word on updating to electron 4 to fix this issue?

**Comment by bitojoe** [comment]
For Mac users, you'll want to open your ~/applications/ folder, ctrl-click the app > "Show package contents" and then navigate and continue using @ddsol's instructions. (Thanks for a solution btw)

One difference is that I used Electrons asar command line tool which you can checkout here:
https://github.com/electron/asar

**Comment by mpwm** [comment]
@bitojoe 
I don't suppose you'd be willing to explain in a bit more detail how you did that, would you? I'm pretty new at all this (though I do have a fair amount of experience with javascript and web development). I just did a fresh install on Catalina on my MacBook Pro (Retina, 15-inch, Mid 2015), and I'm experience the same problem. I tried to follow your instructions, but I'm just getting a javascript error. 

- I assumed that I could ignore the  7zip / index.js parts of the instructions from @ddsol because 7zip is not a mac-compatible app anyway.
- All I did was "show package contents," open the app.asar file and replace the block of code as instructed. Saved, closed, tried to execute the program to no avail.
- I don't understand the significant of the asar command line tool you mentioned, which is probably the main issue here. I downloaded the files from the github link you provided, but I don't know what I'm supposed to do with them. Don't suppose there's a tutorial or something you'd recommend?

**Comment by chemicaldanny** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Thanks! Worked for me (OSX 10.12.6), gonna patch my windows machine at home tonight.

**Comment by ajbobo** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Worked for me. Thanks!

**Comment by eythian** [comment]
I don't know for sure if it's related, but now GMDP doesn't seem to populate the hamburger menu with its own settings option, nor does it respond to media keys for me.

**Comment by JackalFrost** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Works great, thanks for saving me the trouble!

**Comment by cable729** [comment]
Instead of patching, can we fix this and release an update?

**Comment by dobesv** [comment]
I guess @MarshallOfSound is not maintaining this project or something.  Or just on a long holiday.  Or just hasn't gotten around to it yet?

**Comment by Chronos-Sk** [comment]
What's the etiquette on poking a project maintainer?

(Also, updated app.asar worked for me. Thanks!)

**Comment by jostrander** [comment]
I could PR this in for a fix, but ultimately it wouldn't get released until @MarshallOfSound creates the release, windows and mac builds are signed with his certs/keys.

**Comment by MikeKing67** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Thanks, that sorted this issue for me!!!

**Comment by jostrander** [comment]
Also for what its worth. The asar is going to probably be system (windows,linux,mac) dependent. If you copy the ASAR posted here it will more than likely break things that weren't meant for your system to due the native modules not being loaded in that asar.

**Comment by garrett-griffin** [comment]
> @tpetersen50 thanks!
> [app-asar.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3754476/app-asar.zip)
> Here's my patched one. It's just got the extra line added as per @tpetersen50 - but use at your own risk.

Thankyou! Worked here as well.

**Comment by kerfall** [comment]
Thanks for the patch! just in time for the holidays :-)

**Comment by eythian** [comment]
> This is probably related to you possibly being on mac and loading a windows app.asar, or similar.

Definitely possible, I'm on Linux. I'll have a go figuring out how to edit it myself in the weekend if I get the chance.

**Comment by Chronos-Sk** [comment]
Here's the fixed version I'm using for Linux. Caveat emptor, of course.

[app_asar_amd64_deb.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3774084/app_asar_amd64_deb.zip)

**Comment by eythian** [comment]
> Here's the fixed version I'm using for Linux. Caveat emptor, of course.
> 
> [app_asar_amd64_deb.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3774084/app_asar_amd64_deb.zip)

fwiw, that works worse for me:

```
$ google-play-music-desktop-player 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: _electron.app.requestSingleInstanceLock is not a function
    at /usr/share/google-play-music-desktop-player/resources/app.asar/build/index.js:81:31
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/index.js:225:3)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/index.js:226:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/electron.asar/browser/init.js:188:3)
```
and the player window never opens.

**Comment by eythian** [comment]
OK, I found that on Ubuntu the `asar` snap lets you work with the archive, with that I was able to apply the changes and it works again, including media keys and settings option in the menu. Attached is my archive, for amd64:
[app-debian-amd64.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3778273/app-debian-amd64.zip)

**Comment by Chronos-Sk** [comment]
> fwiw, that works worse for me:

Strange, seems like the problem in electron/electron#14057. Could your installation be targeting a different Electron version?

**Comment by jostrander** [comment]
@ddsol I hope you don't mind; I implemented your change in a branch and will PR it in pending another maintainer approves. At the very least people who use the CI builds can use it without the app.asar swaps.

**Comment by MarshallOfSound** [comment]
Sorry folks I've been running a custom build for a few months that apparently doesn't have this issue 😄 Thanks to the solid work from folks in this thread and @jostrander the PR has landed and hopefully we can get something out to everyone this week.

Please note that anyone messing with their install files may not receive automated updates.

**Comment by DHOMD** [comment]
> Fix available (for Windows, at least):
> 
>     * Install [7zip](https://www.7-zip.org/) (at your own risk)
> 
>     * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)
> 
>     * Make sure GDMP is closed, exited and shut down
> 
>     * Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
> 
>     * Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
> 
>     * Open `app.asar` with 7zip (open as archive)
> 
>     * In 7zip, navigate to `build\renderer\windows\GPMWebView\`
> 
>     * Drag `index.js` from there to your desktop or some folder
> 
>     * Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/) at your own risk)
> 
>     * Change
>       ```js
>       function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>       
>       global.isGPM = true;
>       ```
>       
>       
>       to
>       ```js
>       function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>       
>       window.customElements.upgrade = window.customElements.upgrade || function(){};
>       
>       global.isGPM = true;
>       ```
>       
>       
>       (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
> 
>     * Save it or it's as if you did nothing
> 
>     * Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
> 
>     * Close 7zip
> 
>     * Start your music player, it should work now
> 
>     * Clean up the straggling `index.js` and if you're happy, confident and brave, your `app.asar.backup`. Also, clean your desk.
> 
>     * Do this each time you want to run it.
> 
>     * Just kidding, it'll work from now on.

Thank You
Should pin this in open issues ;)

**Comment by jason-mehmel** [comment]
> Sorry folks I've been running a custom build for a few months that apparently doesn't have this issue  Thanks to the solid work from folks in this thread and @jostrander the PR has landed and hopefully we can get something out to everyone this week.
> 
> Please note that anyone messing with their install files may not receive automated updates.

Clarifying, does that include all builds including Linux?

**Comment by DHOMD** [comment]
While I **HIGHLY** recommend using the directions above and doing it yourself.  It's easy and works.

If for some reason you cannot modify the files, I have posted the modified index.js and fully modded app.asar here (mainly for my own convenience since I use this app on multiple computers):  
https://github.com/DHOMD/google_music_desktop

It works for me, I offer no additional support or warranty ;)

**Comment by rzfzr** [comment]
> While I **HIGHLY** recommend using the directions above and doing it yourself. It's easy and works.
> 
> If for some reason you cannot modify the files, I have posted the modified index.js and fully modded app.asar here (mainly for my own convenience since I use this app on multiple computers):
> https://github.com/DHOMD/google_music_desktop
> 
> It works for me, I offer no additional support or warranty ;)

Works for me as well, thanks!

**Comment by jwarkentin** [comment]
Shouldn't this remain open until the fix is actually released for visibility since it's affecting everyone? After wasting way too much time trying to figure out what was going on and fix it, I came and searched the issues here to see if other people were having a problem. I didn't see anything and almost opened a new issue before thinking to check the closed issues. Any reason we can't get a quick patch release?

**Comment by jostrander** [comment]
Pinned the issue for visibility, I spoke with @MarshallOfSound and he's hoping to get a release out soon.

**Comment by TeaWithLucas** [comment]
@jostrander, will the hoxfix mentioned above affect the updated release?

**Comment by lursel** [comment]
> OK, I found that on Ubuntu the `asar` snap lets you work with the archive, with that I was able to apply the changes and it works again, including media keys and settings option in the menu. Attached is my archive, for amd64:
> [app-debian-amd64.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3778273/app-debian-amd64.zip)

Can you explain what you did? I replaced my /usr/share/gpmdp/resources/app.asar with yours, but I still get stuck on loading Library.

**Comment by epikMaowPhailure** [comment]
Still having this issue. Not closed.

**Comment by rameezv** [comment]
@epikMaowPhailure @TeaWithLucas  if you checkout the code and run `yarn run make` for your OS (`yarn run make:deb:64` for 64 bit debian for example), the built version will work fine. Just mentioning in case you need a fix before the next release of GPMDP is put out

**Comment by 0Cyphr** [comment]
> Fix available (for Windows, at least):
> 
> * Install [7zip](https://www.7-zip.org/) (at your own risk)
> * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)
> * Make sure GDMP is closed, exited and shut down
> * Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
> * Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
> * Open `app.asar` with 7zip (open as archive)
> * In 7zip, navigate to `build\renderer\windows\GPMWebView\`
> * Drag `index.js` from there to your desktop or some folder
> * Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/) at your own risk)
> * Change
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   global.isGPM = true;
>   ```
>   
>   
>   to
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   window.customElements.upgrade = window.customElements.upgrade || function(){};
>   
>   global.isGPM = true;
>   ```
>   
>   
>   (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
> * Save it or it's as if you did nothing
> * Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
> * Close 7zip
> * Start your music player, it should work now
> * Clean up the straggling `index.js` and if you're happy, confident and brave, your `app.asar.backup`. Also, clean your desk.
> * Do this each time you want to run it.
> * Just kidding, it'll work from now on.

Thank you, my man. You're a life saver. :)

**Comment by manuelhe** [comment]
Today I got this same problem. This is the log I get in dev mode:
![Screenshot from 2019-11-20 14-36-06](https://user-images.githubusercontent.com/334509/69271984-d804f600-0ba3-11ea-9652-529ac4061317.png)

**Comment by alexd310** [comment]
Got the same issue today as well :
**OS:** 
Windows 10 version 1903 build # 18362.476
**GPMDP Version:** 
4.6.1

**Comment by asychev** [comment]
Same issue

**Comment by shawnrosspeters** [comment]
I'm having this same issue.

MacOS 10.14.6

**Comment by ngrealish** [comment]
One more
MacOS 10.14.6 as well

**Comment by lupynua** [comment]
Same, latest windows 10

**Comment by jaunt** [comment]
Same issue MacOS 10.13.6

**Comment by 0Cyphr** [comment]
Working fine for me on Windows (7 & 10) after using the fix by ddsol.

**Comment by magnosis** [comment]
FIXED INSTALLER: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts

I'm confused...

On Oct 28, this was fixed in the master branch
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3651

But it still does not work when installed form the main site (v4.6.1):
https://www.googleplaymusicdesktopplayer.com/#!

It works if downloaded from the latest Continuous-Integration build:
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts

Why is the official site not including the fix, since it was merge in master (see #3651)?

Can we not close this thread?

**Comment by jostrander** [comment]
4.6.1 was released last year and there hasn't been a release since.

**Comment by GuyTechie** [comment]
Since this is now fixed, can you create a new release with the fix?  4.6.2?

**Comment by ramblingenzyme** [comment]
Why on earth is there a whole year's worth of development on this app that isn't in the hands of users???

**Comment by ajkuftic** [comment]
Just FYI. The ASAR file linked here just needs to be added to /Applications/Google Play Music Desktop Player/Contents/Resources and it fixes the issue on macOS. Take a backup of the old ASAR file first. 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-547554696

**Comment by jwarkentin** [comment]
The problem with the solution posted here for those of us using snap packages is you can't modify them. The snap has to be updated and until that happens it's basically unusable. Please cut a release! @MarshallOfSound

**Comment by magnosis** [comment]
Not all of your users are computer geeks. Most aren't. There's already a fixed package that doesn't rely on users copying files around and hacking zip archives...

Please cut a new official release?

**Comment by rameezv** [comment]
For everyone who needs a fix and can't compile their own, here are links for the latest CI releases. I haven't confirmed all OSes except MacOS and Debian 64-bit, but the rest should also work.

[Windows](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)

[MacOS](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)

[Debian (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb)

[Debian](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_i386.deb)

[Red Hat (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.x86_64.rpm)

[Red Hat](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.i386.rpm)

@jwarkentin @ramblingenzyme @GuyTechie

**Comment by jwarkentin** [comment]
@rameezv Thanks for doing that! Unfortunately, that doesn't help with my snap package issue unless I want to replace it with a standard `.deb` package but hopefully that helps a lot of people. In the meantime, I have a difficult and painful but functional way to get it working for myself :-\

**Comment by jostrander** [comment]
For what it's worth I believe I merged in a patch from @RAOF that should create an automatic build on launchpad for the edge channel if you want to give that a shot.

**Comment by RAOF** [comment]
The edge channel should indeed contain a build with this fix. (Among other goodies).

I've not noticed any problems; perhaps I should also promote it to stable, although I was going to wait for a release to do that.

At least, it works for me 😀

**Comment by jwarkentin** [comment]
@RAOF 

> The edge channel should indeed contain a build with this fix. (Among other goodies).
> 
> I've not noticed any problems; perhaps I should also promote it to stable, although I was going to wait for a release to do that.
> 
> At least, it works for me

I just updated to edge and it still doesn't work. It says edge was released on 9/13/2019 but the fix wasn't committed until 10/28/2019.

**Comment by mobusby** [comment]
Edge channel snap package now works for me -- looks like the snap was updated today.

**Comment by dedayosam** [comment]
Thanks @rameezv for the release links. The MacOS build worked for me.

**Comment by Rdstrmfblynch79** [comment]
I had the 4.1 installer from when I first installed the program, so I uninstalled the newest version and installed from 4.1. That does seem to work without issue, so I think this is an issue related to 4.6+

**Comment by LordRasa** [comment]
@Rdstrmfblynch79 Thank you for that. The [Version 4.1.1](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.1.1) works just fine for now on Windows10 v.1903

**Comment by felipezacani** [comment]
This is happening again for me, 4.6.1, Windows 10.

**Comment by jostrander** [comment]
4.6.1 from the releases tab or website or from a link somewhere in one of these threads? If you are using the builds from the website those are still broken.

**Comment by felipezacani** [comment]
> 
> 
> 4.6.1 from the releases tab or website or from a link somewhere in one of these threads? If you are using the builds from the website those are still broken.

Tried every version I could. Website, releases tab and even chocolate, same result.

**Comment by rameezv** [comment]
@felipezacani None of those sources are the fixed one. for Windows, try [this](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe) as per my [earlier comment](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367)

**Comment by ignoregami** [comment]
@rameezv Just chiming in that I experienced the reported issue and the 4.6.1 alpha resolved it for me.  Thanks for the quick resolve!

**Comment by ignoregami** [comment]
Maybe I should clarify that I mean the version you linked since it appears that 4.6.1 is ambiguous here.

**Comment by jordinja** [comment]
Has Samuel Attard @MarshallOfSound stepped down from this project now? Is he the only one with access to update the website? I'd be happy to help with updating the download links if he doesn't get time to do so himself these days - I'm no coder but it can't be that hard, right?

**Comment by christofdamian** [comment]
> Has Samuel Attard @MarshallOfSound stepped down from this project now? Is he the only one with access to update the website? I'd be happy to help with updating the download links if he doesn't get time to do so himself these days - I'm no coder but it can't be that hard, right?

I am not sure how active he still is. Might be worth pinging him on Twitter. 

What we really need is a new release, the current one is not usable for a lot of people. 
4.6.1 is about 18 months old now.

**Comment by Iowerth** [comment]
Just installed last version from this [post](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367) and nothing changed except for now player stucks not at "Loading music library" but at this:
[url=https://i.imgur.com/bE3riMO.jpg][img]http://i.imgur.com/bE3riMOm.jpg[/img][/url]
Windows 7 x64 on work PC (now).
Will try at home on home PC.

**Comment by landesko** [comment]
Having the same issue as well!

**Comment by mtuma5672** [comment]
@rameezv Thanks for 4.6.1 Alpha, that is working for me on Windows 10. I have not tried Mac yet - will have to compile??

**Comment by rameezv** [comment]
@mtuma5672  Nope! [Here](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)'s the link for MacOS

**Comment by sydsilverwolf** [comment]
Been using this program for a year. Just decided to stop working today, stuck at "Loading Music Library". **Uninstalled**. Solved my problem. Not using app anymore.

**Comment by rameezv** [comment]
@sydsilverwolf what a supremely unproductive comment

**Comment by Iowerth** [comment]
> 
> 
> Just installed last version from this [post](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367) and nothing changed except for now player stucks not at "Loading music library" but at this - https://i.imgur.com/bE3riMO.jpg
> Windows 7 x64 on work PC (now).
> Will try at home on home PC with Windows 10 x64. Upd: all is fine at home with this version.

This version still doesn't work on Windows 7 x64. Additionally checked **index.js** in `\app.asar\build\renderer\windows\GPMWebView` to ensure if `window.customElements.upgrade = window.customElements.upgrade || function(){};` not present there. But this code is there.

**Comment by nico-vromans** [comment]
> Fix available (for Windows, at least):
> 
> * Install [7zip](https://www.7-zip.org/) (at your own risk)
> * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)
> * Make sure GDMP is closed, exited and shut down
> * Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
> * Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
> * Open `app.asar` with 7zip (open as archive)
> * In 7zip, navigate to `build\renderer\windows\GPMWebView\`
> * Drag `index.js` from there to your desktop or some folder
> * Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/) at your own risk)
> * Change
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   global.isGPM = true;
>   ```
>   
>   
>   to
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   window.customElements.upgrade = window.customElements.upgrade || function(){};
>   
>   global.isGPM = true;
>   ```
>   
>   
>   (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
> * Save it or it's as if you did nothing
> * Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
> * Close 7zip
> * Start your music player, it should work now
> * Clean up the straggling `index.js` and if you're happy, confident and brave, your `app.asar.backup`. Also, clean your desk.
> * Do this each time you want to run it.
> * Just kidding, it'll work from now on.

@ddsol, I've tried this on Mac (Catalina) and can happily say it works here too. So thanks a bunch!

Addendum for Mac users: follow these steps:
1. to unpack and repack the `app.asar` install npm (comes bundled with NodeJS): https://nodejs.org/dist/v12.13.1/node-v12.13.1.pkg
2. install asar:
`npm install -g asar` (`-g` installs it globally, so you can use it anywhere, this also helps keep the GPMDP directory structure free from additional clutter)
3. navigate to the proper directory:
`cd /Applications/Google\ Play\ Music\ Desktop\ Player.app/Contents/Resources/`
4. backup the original `app.asar`:
`cp app.asar app.asar.backup`
5. unpack the `app.asar`:
`asar extract app.asar source_code` (you can replace the `source_code` with whatever you like, just remember this for later)
6. change the above-mentioned file (again, thanks @ddsol)
7. repack the source code:
`asar pack source_code app.asar` (if chosen another name than `source_code` in step 5, use it here again, this will also override the existing `app.asar`)
8. verify everything works
9. remove the backup:
`rm -rf app.asar.backup`

**Comment by nico-vromans** [comment]
> Fix available (for Windows, at least):
> 
> * Install [7zip](https://www.7-zip.org/) (at your own risk)
> * Install [Asar7z](http://www.tc4shell.com/en/7zip/asar/) (at your own risk, it could have a large number of hairy viruses)
> * Make sure GDMP is closed, exited and shut down
> * Find your GDMP install (`C:\Users\You\AppData\Local\GPMDP_3\app-4.6.1\resources`)
> * Make a backup copy of `app.asar` to `app.asar.backup` in the same folder
> * Open `app.asar` with 7zip (open as archive)
> * In 7zip, navigate to `build\renderer\windows\GPMWebView\`
> * Drag `index.js` from there to your desktop or some folder
> * Edit the file with an editor that can handle linux file endings (not Notepad, but you can use [Notepad++](https://notepad-plus-plus.org/) at your own risk)
> * Change
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   global.isGPM = true;
>   ```
>   
>   
>   to
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   window.customElements.upgrade = window.customElements.upgrade || function(){};
>   
>   global.isGPM = true;
>   ```
>   
>   
>   (If you can't find it because your version is different, you can add the line at the top, the bottom, or anywhere outside a block)
> * Save it or it's as if you did nothing
> * Drag the `index.js` file back into 7zip into the same `GPMWebView` packed folder where you got it from, and when 7zip as asks if you want to copy the file into the archive, you can say "yes" because you made a backup so if you made a mistake you can put it back to it's original non-functional state.
> * Close 7zip
> * Start your music player, it should work now
> * Clean up the straggling `index.js` and if you're happy, confident and brave, your `app.asar.backup`. Also, clean your desk.
> * Do this each time you want to run it.
> * Just kidding, it'll work from now on.

**Comment by VitaliiUr** [comment]
The same issue. Ubuntu 18

**Comment by jordinja** [comment]
> For everyone who needs a fix and can't compile their own, here are links for the latest CI releases. I've only been able to confirm it works on MacOS and Debian 64-bit, but the rest should also work.
> 
> [Windows](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)

This version fixed the issue for me as well, by the way - thanks @rameezv :)

**Comment by sergjoker** [comment]
@rameezv Thanks man, your comment saved me from lots of boring stuff :)

**Comment by slowbro** [comment]
> [Debian (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb)

This package works for me on Arch Linux, for rebuilding the [AUR gpmdp package](https://aur.archlinux.org/packages/gpmdp).

**Comment by jeffreydwalter** [comment]
For what it's worth, I'm running Version 4.6.1 (4.6.1) on macOS. It was working fine until I hit CMD-R. Now I'm stuck at the "Loading Music Library" screen.

**Comment by Flinlock** [comment]
> @mtuma5672 Nope! [Here](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)'s the link for MacOS

Thanks! Worked for me on the latest version of Catalina.

**Comment by adkuca** [comment]
> > For everyone who needs a fix and can't compile their own, here are links for the latest CI releases. I've only been able to confirm it works on MacOS and Debian 64-bit, but the rest should also work.
> > [Windows](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)
> > [MacOS](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)
> > [Debian (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb)
> > [Debian](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_i386.deb)
> > [Red Hat (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.x86_64.rpm)
> > [Red Hat](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.i386.rpm)
> > @jwarkentin @ramblingenzyme @GuyTechie
> 
> Windows version works fine on Windows 10, 1909. Thank you

I had the issue on windows 10 and this version worked.

**Comment by rafaelanastacioalves** [comment]
> For everyone who needs a fix and can't compile their own, here are links for the latest CI releases. I've only been able to confirm it works on MacOS and Debian 64-bit, but the rest should also work.
> 
> [Windows](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)
> 
> [MacOS](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)
> 
> [Debian (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb)
> 
> [Debian](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_i386.deb)
> 
> [Red Hat (64-bit)](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.x86_64.rpm)
> 
> [Red Hat](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/redhat/google-play-music-desktop-player-4.6.1.i386.rpm)
> 
> @jwarkentin @ramblingenzyme @GuyTechie

Worked for me on Mac. Thanks!
I wonder wether will they be available on normal download channels. 
Regards,

**Comment by kieranxsomer** [comment]
I literally created a github account so i could come in and comment, the new version fixed it and now i can get back to illustration jobs ;P can't do drawy jobs without music!!

**Comment by hisuwh** [comment]
Is there a non hacky fix for this going out anytime soon?

**Comment by rameezv** [comment]
@hisuwh no hacks in this solution: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367 just use the installer link from here. Simple!

**Comment by hisuwh** [comment]
Thanks.  That was in the hidden items.  How come there hasn't been a proper release published since July 2018?

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases

**Comment by rameezv** [comment]
@hisuwh 

@MarshallOfSound seems like he's been pretty busy for the last year. He did mention that a release is coming soon but in the meantime the CI builds are available.

**Comment by TheDavidJohnson** [comment]
On Ubuntu 18.04, I was unsuccessful in getting the CI build to work. At first I just downloaded and installed, but then uninstalled and reinstalled. No joy.

Thankfully, just [switching to DEV MOVE](#issuecomment-541445516) solved the problem for me. Just took a few seconds and now I'm jamming again for the first time in a while. Thanks @jostrander!

**Comment by smelnyk-va** [comment]
> @mtuma5672 Nope! [Here](https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)'s the link for MacOS

Thanks Rameez! This totes fixed my issue. :D

**Comment by rameezv** [comment]
@smelnyk-va no prob, and fancy running into you here! Hope you're well!

**Comment by musichemist** [comment]
> [Windows](https://ci.appveyor.com/api/buildjobs/8j7bmpy1lk1aw3y3/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)

Working on W7Pro 64. Made a GitHub account just to say Thank You to @rameezv for this.

**Comment by smelnyk-va** [comment]
@rameezv Haha no kidding! Things have been great! I hope things have been well for you as well!

**Comment by davidhouchin** [comment]
Thanks so much for the updated CI packages. This fixes the player for me in Fedora 31, coming from the broken Flatpak package.
Not sure if 4.6.1 is globally affected (my friend's MacOS version ran into this issue weeks before mine) but I hope maintainers can get a hotfix or new release pushed out soon.

**Comment by Bllacky** [comment]
Please, for the love of God, make a new proper release!

**Comment by JonnoN** [comment]
this is "Closed" because the solution is to download an exe from some random website? What?

**Comment by rameezv** [comment]
@JonnoN it's not a random website, it's the automated continuous build that is generated when code is merged into the master branch. You can access it from the README.md. The issue is closed because the code to fix it has been merged.

**Comment by Bllacky** [comment]
> 
> 
> @JonnoN it's not a random website, it's the automated continuous build that is generated when code is merged into the master branch. You can access it from the README.md. The issue is closed because the code to fix it has been merged.

Ok, and the rest of the planet who doesn't go through the Readme and the Github issues comments,  they will continue to download a broken version from the official channels. I agree, this issue should be closed, we have a solution, but please, don't ignore the need for a proper, new release.

**Comment by rameezv** [comment]
@Bllacky I understand that, and if I had the ability to make a release, I would. But until @MarshallOfSound makes a release the CI links are the best solution.

**Comment by jgspratt** [comment]
How do we get at the latest CI builds (e.g., for mac) without having someone post magic links here?

**Comment by davidhouchin** [comment]
@jgspratt On the homepage of this project, there are badges for the builds near the top of the readme.
Click the MacOS/Linux badge, then click the last successful build marked "gather artifacts".

For me at least, I don't see any "artifacts" tab, so append the URL with `#artifacts/containers/0` and you should get a list of the generated artifacts, MacOS being Darwin.

For Windows, you can click the AppVeyor badge, and I _do_ see an artifacts tab there to download.

**Comment by jgspratt** [comment]
Great thanks.  That worked.  I got https://3751-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip as my latest.

**Comment by dralph** [comment]
> Fix available (for Windows, at least):
> ...
> * Change
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   global.isGPM = true;
>   ```
>   
>   to
>   ```js
>   function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
>   
>   window.customElements.upgrade = window.customElements.upgrade || function(){};
>   
>   global.isGPM = true;
>   ```

Worked for me in OS X (using npx asar to extract and repack the file)
All the thank yous.
