### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by betmakh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3693]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS: MAC OS Catalina 10.15.1 **

**GPMDP Version: 4.6.1**

**Issue Descriptions: Can't login any more**

**Steps to Reproduce: 

1. Delete your data folder ~/Library/Application Support/Google Play Music Desktop Player. I did it because got stucked on Loading your library screen)
2. Open app and try to login
3. Login fails with info that my browser is not secure for logging in: 

> Couldn't sign you in
> 
> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> 
> Try using a different browser. Learn more

![image](https://user-images.githubusercontent.com/7427467/69809791-bda5ca80-11ea-11ea-97a2-b72690bda532.png)

P.S. I tried to disable 2 factor auth for the google account but it didn't help
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3900831/debug_info.zip)

**Comment by Mallox51** [comment]
Same problem for me here, with macOS 10.15.1 Catalina
I'm stuck on 
<img width="1001" alt="Screenshot 2019-11-28 at 12 09 29" src="https://user-images.githubusercontent.com/630338/69801823-6e569e80-11d8-11ea-927d-d1588175d794.png">

- tried to delete my ~/Library/Application Support/Google Play Music Desktop Player directory.
- Logged me in again
- Stuck on the same screen again

**Comment by rijnhard** [comment]
same here But Linux Mint 19

**Comment by nlmunro** [comment]
Same here on Windows 10, tried allow less secure app login (https://myaccount.google.com/lesssecureapps), but no change.

**Comment by nlmunro** [comment]
There is a fix for it here and it works :-)
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts

See: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660

**Comment by conradfr** [comment]
The CI build fix the splashscreen hang but I can't use the scrollbar (mouse wheel works).

**Comment by rembk4y** [comment]
Confirm, same problem here, Linux Mint 19.2

**Comment by JeffLCoughlin** [comment]
Same for me on Mint 19.2 and RHEL 7

**Comment by kroppt** [comment]
Also a problem on Windows 10

**Comment by chasfh** [comment]
Windows 7 also.

**Comment by AntonioMichaelAlvarez** [comment]
Same, Xubuntu 16.04.6 LTS, GPMDP 4.6.1 Debian 64-bit *.deb

**Comment by danryandesigns** [comment]
Couldn't sign you in
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more

Same issue. Windows 10.

**Comment by 8simsim8** [comment]
Confirm, same problem: macOS 10.15.1 Catalina

**Comment by jostrander** [comment]
I am closing this in favor of the pinned #3545. It appears to be now effecting more of you now that we are closer to the end of the year deadline that Google was imposing, but in theory is fixed in the next release.

**Comment by betmakh** [comment]
> I am closing this in favor of the pinned #3545. It appears to be now effecting more of you now that we are closer to the end of the year deadline that Google was imposing, but in theory is fixed in the next release.

Hi @jostrander I checked the thread and pr. I also pulled the code change which should fix the issue and rebuilt project locally but it does not fix the issue.

After checking the project's code and electron docs: https://electronjs.org/docs/api/webview-tag I think the issue here is that app uses <webview> tag to authorize user. Which can mean project's architecture needs to be changed to use google libs to auth user instead. 

I think the Issue should remain open

Thanks

**Comment by jostrander** [comment]
@betmakh The issue is indeed that the application uses the web view tag. Unfortunately there is no other way for us to integrate with GPM and YTM as far as authentication goes.  We are simply injecting functionality into the existing web apps that Google provides via the web frame. 

I'm not sure why the latest changes didn't fix the issue for you, unless Google has changed the way they check for third party "browsers" again. Either way it should be tracked in the existing issue, IMO.

**Comment by aachowhan** [comment]
Same issue on Windows 10.

**Comment by Recif2** [comment]
Same issue here (Windows 10 / Chrome 78.0.3904.108

**Comment by mojhale** [comment]
I found a solution to the same issue for me with [this post ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545#issuecomment-567636797)on the related thread linked above.
