### ISSUE TITLE
Windows - mini player controls are off-screen

### ISSUE THREAD

**Issue by t-readyroc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#401]
First noticed this last night after upgrading at home, & now I'm noticing it at work as well.  Once the player is minimized, controls appear off the side of the screen.

**OS:** - Windows 10 (both home & work)

**Issue Descriptions:** - mini player controls off-screen

**Steps to Reproduce:** - minimize player; unable to then control player

**Screenshot** - http://i.imgur.com/eP29652.png

**Comment by MarshallOfSound** [comment]
I just tried your steps to reproduce.  And they didn't reproduce it :cry: 

Are you sure you aren't doing anything else in those steps?

**Comment by t-readyroc** [comment]
OK, I've sort it out - you should be able to reproduce this:

1. open player
2. open side menu (3 bars, top-left)
3. minimize player

If you don't have the side menu open, the controls display correctly, but if the side menu is open when you minimize, they're f'ed.

**Comment by MarshallOfSound** [comment]
It sounded like those steps would do it, but nope... I still can't reproduce this glitch.  Any other ideas?

**Comment by t-readyroc** [comment]
OK, very odd.  It seems that if you do the above 3 steps _after_ you've already minimized once w/o menu successfully, it works.  **BUT** if you do the above 3 steps straight from a freshly opened player, you get the controls off-screen.  Definitely erratic.

**Comment by MarshallOfSound** [comment]
I just did a clean run and did the following

1. Open the side nav
2. Play a song
3. Click the mini player button

And it works fine?  How consistently does it happen for you?

**Comment by t-readyroc** [comment]
Every time.  But I suppose I have a workaround if you want to push this to the back of the queue.

I guess the only other thing to mention is that I go to My Library & hit the shuffle button to play, rather than picking a particular song.

**Comment by jessecr** [comment]
I can reproduce this as well. Upon first opening the program I

1. Open the side nav
2. Click the mini player button

And the controls are off to the side (as seen in the screenshot in the initial comment) and I cannot return to the full view without quitting.

If I click the mini player button before opening the side nav, the controls will be visible as expected.

Windows 7 64-bit SP1

**Comment by MarshallOfSound** [comment]
Goddamit, googles A/B testing....  If anyone can run the dev version and try figure out whats going on it would be much appreciated

**Comment by jason-mehmel** [comment]
Also experiencing this on Debian Linux (Bunsen Labs).

**Comment by MarshallOfSound** [comment]
Looks like the google update just went live.  I'm going to be pushing out an urgent fix in the next few hours

**Comment by MarshallOfSound** [comment]
Fixed in master, doing a release soon

**Comment by jason-mehmel** [comment]
Still experiencing this issue in Debian Linux. (Bunsen Labs) Most recently installed 3.0.1

**Comment by MarshallOfSound** [comment]
@jason-mehmel I have tested on multiple platforms including various distros of linux and the issue is fixed.  It sounds like you have a dodgy install, can you do a completely clean install

**Comment by jason-mehmel** [comment]
Hey there, I downloaded the 64 bit .deb file, used the GDebi package manager to first remove the program and then install it, and I'm still experiencing the issue.

In terms of a clean install, should I also be tracking down the config files & such? (I noticed my settings remained even after the re-installation.)

Also, should we change the name of this issue to take Windows off of it?

**Comment by MarshallOfSound** [comment]
Settings are stored in the `~/.config` folder but you shouldn't have to delete them.  Can you find the actual install directory and manually delete the files there, then reinstall (sounds stupid but might work)
