### ISSUE TITLE
Colored window border on first run after booting.

### ISSUE THREAD

**Issue by TorgeirHolm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#981]
On the first run after booting the computer, the window border is brightly colored in what seems to be the same color I have selected as accent color in the dark theme. After quitting, the player restarts with the normal dark border color. 

Windows 10

**Comment by MarshallOfSound** [comment]
@TorgeirHolm This issue has been reported once before and we think we fixed it in master.  Just to check, is your issue reproachable.  I.e. Can you make it happen again right now :+1:

**Comment by TorgeirHolm** [comment]
Yes, it still happens, see the attached screenshot from just now. Version 3.2.1, Windows 10.

You can also see the 8px ghost border (the other issue) on the left hand side in the same screenshot taken while maximized on my rightmost 1920×1080 monitor. Note that the screenshot dimensions are 1928×1080. 

![screenshot 2016-04-23 12 42 26](https://cloud.githubusercontent.com/assets/18615991/14760915/fc9c1fd8-0950-11e6-9d87-3f0b665559f4.png)

**Comment by MarshallOfSound** [comment]
Would you mind uninstall the version you have and installing this one https://ci.appveyor.com/api/buildjobs/2tpv3tkpavdovvf9/artifacts/dist/installers/win32/Google%20Play%20Music%20Desktop%20PlayerSetup.exe

Just to see if we have actually fixed the issue.  If we have you should reinstall the original version or you won't get updates :+1:

**Comment by TorgeirHolm** [comment]
Yes, this one has no colored border! (but throws a script error on start, and has no tray icon).

![screenshot 2016-04-23 14 03 47](https://cloud.githubusercontent.com/assets/18615991/14761312/1193955e-095d-11e6-97d4-5920fe5ad0d9.png)

**Comment by MarshallOfSound** [comment]
The tray icon looks a bit different now and might be in your extended tray
menu.

That DLL error is to be expected

**Comment by TorgeirHolm** [comment]
It's not in the extended tray. Also minimize doesn't work. But I'll report that if it happens on the official builds. Reverting back to that now.
